# Generated by Django 6.0.3 on 2026-03-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='feedback',
        ),
    ]
